include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/firebase_options.dart"
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
