name: word_tiles_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  flutter_animate: ^4.5.0
  confetti: ^0.7.0
  google_fonts: ^6.2.1
  audioplayers: ^6.1.0
  flutter_soloud: ^4.1.7
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/levels/english/
    - assets/levels/portuguese/
    - assets/levels/russian/
    - assets/levels/spanish/
    - assets/levels/turkish/
    - assets/levels/german/
    - assets/levels/french/
    - assets/levels/italian/
    - assets/levels/vietnamese/




