// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxJysDEKQEAf-YQR7ofwlLzoLUbuhsTZs',
    appId: '1:949964208375:web:a4fa2e51775b8f5bda3bf2',
    messagingSenderId: '949964208375',
    projectId: 'fw27-mobgame',
    authDomain: 'fw27-mobgame.firebaseapp.com',
    storageBucket: 'fw27-mobgame.firebasestorage.app',
    measurementId: 'G-YQP1XP14YD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK0v_MTjXbgesfreG_p9i4ewaAB-3uTZ0',
    appId: '1:949964208375:android:067a8c2e038f5b22da3bf2',
    messagingSenderId: '949964208375',
    projectId: 'fw27-mobgame',
    storageBucket: 'fw27-mobgame.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn04DUjcD8fhMlal1nmu4Mssda5hUrUhw',
    appId: '1:949964208375:ios:3278ec1301c49d1cda3bf2',
    messagingSenderId: '949964208375',
    projectId: 'fw27-mobgame',
    storageBucket: 'fw27-mobgame.firebasestorage.app',
    iosBundleId: 'com.wordtiles.wordTilesFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn04DUjcD8fhMlal1nmu4Mssda5hUrUhw',
    appId: '1:949964208375:ios:3278ec1301c49d1cda3bf2',
    messagingSenderId: '949964208375',
    projectId: 'fw27-mobgame',
    storageBucket: 'fw27-mobgame.firebasestorage.app',
    iosBundleId: 'com.wordtiles.wordTilesFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxJysDEKQEAf-YQR7ofwlLzoLUbuhsTZs',
    appId: '1:949964208375:web:046d10458ba39caeda3bf2',
    messagingSenderId: '949964208375',
    projectId: 'fw27-mobgame',
    authDomain: 'fw27-mobgame.firebaseapp.com',
    storageBucket: 'fw27-mobgame.firebasestorage.app',
    measurementId: 'G-CJJWXE13HK',
  );
}
